### ISSUE TITLE
Upgrades?

### ISSUE THREAD

**Issue by mikekenyon99** [myspaghetti/macos-guest-virtualbox#108]
Hi,

Is it possible to write an upgrade script?  They have just released a new sub-version of Catalina and if you use the Apple updater then the Virtualbox crashes on reboot.  Therefore you have to build a new VM (or restore a backup).  This obvously a bit of a pain as you have to reset up your machine again. 

Cheers

Mike

**Comment by myspaghetti** [comment]
Upgrades should work fine. If the VM crashes after an upgrade that's a VirtualBox bug, which is beyond the scope of this script.

**Comment by mikekenyon99** [comment]
Appreicate your quick reponse - I meant my VM crashes not VirtualBox.  Apologies for not being clearer.

Can I just confirm that when you go to Sys Preferences in macOS  Catalina and do an upgrade it should work?  I will try again tonight but it goes through multiple boot cycles etc..   Does it work for you?

**Comment by myspaghetti** [comment]
Sorry, I could not reproduce a crash. I can confirm that using "About This Mac", "Software Update", checking for an update, downloading and installing version `19A602` from the initial release `1985A3` works.

When trying to upgrade from version `1985A3` (initial public release) to Catalina Supplemental Update (`19A602`), the EFI boot script `startup.nsh` boots into the existing version (`1985A3`) instead of the update installer. However, pressing `Esc` and then manually loading the APFS drivers and the installer from `FS[N]:/macOS Install Data/Locked Files/Boot Files/boot.efi` succeeds.

Either way, making `startup.nsh` compatible with post-installation updates or just handling updates in general it's beyond the scope of this script. I'll modify `startup.nsh` to exhaust the search for updates before booting the old version, but I can't troubleshoot VirtualBox crashes or failed boots or failed updates in general.

**Comment by mikekenyon99** [comment]
No that fine, once I had made myself clearer your answer makes better sense. I will test that on my installation. 

Many thanks

Mike

**Comment by Oujiii** [comment]
Hi, I know this issue has already been closed, by I faced the same issue on Mojave. After updating it, my system no longer boots. Now I'm stuck in the EFI shell after reboot.

**Comment by myspaghetti** [comment]
Yes, updating to Catalina results in an unbootable VM because VirtualBox doesn't support the `boot.efi` that comes with Catalina 10.15.2 and 10.15.3. See [issue 134](https://github.com/myspaghetti/macos-guest-virtualbox/issues/134). I am about to write a step-by-step guide for un-hosing a Catalina VM.

**Comment by Oujiii** [comment]
@myspaghetti Sorry for not making myself clear enough. I wasn't updating to Catalina. I'd just made an ordinary security update for Mojave. I can open a new issue if you want to, but I think I'd have to redo everything as I'm not close to that VM at the moment.

**Comment by myspaghetti** [comment]
A new issue would be good. Please include, if you can, the installed version of Mojave (for example Mojave 10.14.4?) and the upgrade version (10.14.6?) and either the file `startup.nsh` or a screenshot of `startup.nsh` running on the EFI Internal Shell.

When I upgrade from 10.14.4. to 10.14.6 everything goes smoothly, but there have been many versions of `startup.nsh` (and some versions of the script without `startup.nsh` at all) so I'd need more details to be able to reproduce the issue.

**Comment by Oujiii** [comment]
Ok, I will try my best. Should be open by tonight or tomorrow. Thanks for the fast replies.
