### ISSUE TITLE
Use aria2c because swcdn.apple.com throttles

### ISSUE THREAD

**Issue by freeload101** [myspaghetti/macos-guest-virtualbox#110]
I experience this with a MAC yesterday and with this script I realize even with wget it's starts out at about 20% then throttles to 8-10 hours .. a bit of a hackjob but I can do a real pull request to replace wget if you want using aria much faster (under 10 minutes)  at just 4 threads using the following.

Required for cygwin:
aria2c
libcares2

`echo "Downloading macOS installation files from swcdn.apple.com"
for filename in "BaseSystem.chunklist" \
                "InstallInfo.plist" \
                "AppleDiagnostics.dmg" \
                "AppleDiagnostics.chunklist" \
                "BaseSystem.dmg" \
                "InstallESDDmg.pkg"; \
    do aria2c --file-allocation=none -c -x 4 -s 4 "${urlbase}${filename}" \
            -o "${macOS_release_name}_${filename}"
			
done`

Yet one more reason to h@te apple ! they throttle there own users ...

**Comment by myspaghetti** [comment]
Thanks but I'm not likely to implement this since `wget` is available on more systems and `aria2` is sort of cutting-edge. Still a great tip for anybody who wants to speed up their download. I could not reproduce the throttling but I've had problems with `curl` in the past which is why I've settled on `wget`.
