### ISSUE TITLE
Merging with / importing from "runMacOSinVirtualBox"?

### ISSUE THREAD

**Issue by AlexanderWillner** [myspaghetti/macos-guest-virtualbox#136]
Nice script. Maybe https://github.com/AlexanderWillner/runMacOSinVirtualBox is an interesting source for you. We might want to consider to merge efforts in the future.

**Comment by myspaghetti** [comment]
Thanks! Your code looks a lot better than mine but I think the time and effort it would take to merge codebases outweigh the benefits. It's rumored that the next macOS will run on ARM processors, and if that's true there's no future for VirtualBox on macOS hosts or for macOS guests. I made this script to create an installer for legacy Macbooks that for some reason couldn't download the macOS installer through the recovery environment. With High Sierra being compatible back to 2009 Macbooks, it was a pretty good compromise between modern features and hardware compatibility, and most importantly it's very easy to download and install. The VirtualBox installation wasn't the goal, it was a tool to get the installer onto a USB drive and install on a genuine Macbook. Since newer Macs are much better at recovery, and future macOS might not be compatible with x86 at all, this script is probably at its maximum usefulness right now, VirtualBox 6.1's NVRAM issue and Catalina 10.15.2 EFI issue notwithstanding.
