### ISSUE TITLE
VM Won't Properly Boot After Script Completion

### ISSUE THREAD

**Issue by RossMadness** [myspaghetti/macos-guest-virtualbox#150]
Maybe I missed a step somewhere, but I follow the script instructions. After it prompts to "Hit enter to restart or manually eject the install VDI", I hit enter. The VM shuts down and the script asks if I want to delete the temp files. After that I boot the VM and it will not get past the built-in EFI shell. I let startup.nsh run and I get the errors listed in the screenshot.
![startupnsherrors](https://user-images.githubusercontent.com/49315869/73216604-e7606c80-411b-11ea-9998-640d697b030c.png)

I've tried escaping out, manually selecting the boot disk from Boot Manager and it doesn't appear to work. I've read through the documentation but I'm not sure what I need to do next. I didn't specify any values to load for EFI/NVRAM settings because I thought the documentation stated it was only necessary if needing iCloud and iMessage (which I don't need).

**Comment by myspaghetti** [comment]
You're correct, this is unrelated to the NVRAM, the open-source APFS EFI drivers for VirtualBox 6.0 and 5.2 are missing, which is why the macOS APFS volume is not bootable.

* Is the file `AppleSupport-v2.0.4-RELEASE.zip` in the script's working directory?
* Is the file `ApfsDriverLoader.efi` in the script's working directory?

If they're missing, either the download failed or the installation failed. You can download them with `./macos-guest-virtualbox.sh prepare_macos_installation_files`. Then you can attach the VISO and base system, boot the base system, then manually mount the target EFI partition and copy the EFI files from the VISO to `/Volumes/path/to/target/EFI/EFI/drivers`.

It's also possible that the script didn't type the command that copies the EFI files correctly, but didn't report an error. I'll look into it.

**Comment by myspaghetti** [comment]
Yes, there's a bug in the script! The EFI drivers aren't being copied! If you haven't deleted the temporary files you can run `./macos-guest-virtualbox.sh populate_macos_target`, or you can run the script from the start if you have the temporary files or not.

Sorry about that! Fixed in [version 0.84.1](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
