### ISSUE TITLE
Getting iMessage to work with VirtualBox

### ISSUE THREAD

**Issue by afillat** [myspaghetti/macos-guest-virtualbox#163]
I have been able to create VM's with High Sierra, Mojave, and Catalina. Used macos-guest-virtualbox script. The VM correctly authenticates the AppleID and iCloud during setup. However, when iMessage is started and AppleID and password are provided, the VM churns for a while and then the login message box refreshes with no app launch. NVRAM parameters modeled on an existing Macbook. Why does iMessage fail after successfully attaching to iCloud and App Store. Any ideas?

**Comment by myspaghetti** [comment]
Run the following commands on your virtual machine and make sure the output matches the genuine Mac exactly:
```
system_profiler SPHardwareDataType
ioreg -l | grep -m 1 board-id
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM
ioreg -l -p IODeviceTree | grep \"system-id
```

**Comment by afillat** [comment]
I did as you suggested using copy/paste to avoid any error. I reran the entire script. Alas the VM did not even authenticate my AppleID during setup, unlike when I used slightly modified parameters. The only difference I noticed was that the System_UUID, unlike in the unmodified script, was formatted without dashes (which I copied exactly) and was not the same as the DmiSystemUUID.

**Comment by myspaghetti** [comment]
The value of `DmiSystemUuid` in the script needs to be equal to the value of `Hardware UUID` from the command `system_profiler SPHardwareDataType`, and the value of SYSTEM_UUID needs to be equal to the value of `system-id` from the command `ioreg -l -p IODeviceTree | grep \"system-id`. Both appear in the script in the exact format they appear on a genuine Mac.

**Comment by afillat** [comment]
Success!!! Thank you so much!

**Comment by myspaghetti** [comment]
Run the following commands on your virtual machine and make sure the output matches the genuine Mac exactly:
```
system_profiler SPHardwareDataType
ioreg -l | grep -m 1 board-id
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM
ioreg -l -p IODeviceTree | grep \"system-id
```

The value of `DmiSystemUuid` in the script needs to be equal to the value of `Hardware UUID` from the command `system_profiler SPHardwareDataType`, and the value of SYSTEM_UUID needs to be equal to the value of `system-id` from the command `ioreg -l -p IODeviceTree | grep \"system-id`. Both appear in the script in the exact format they appear on a genuine Mac.

The Apple ID has to be active, you cannot register a new Apple ID because that would require assigning more NVRAM and SMC values than the script provides.

If you don't have a genuine Mac, [there are guides on the internet for generating genuine-like values](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial), but no support is offered for non-genuine values.

**Comment by myspaghetti** [comment]
See the documentation for applying the NVRAM and EFI values.

Run the following commands on your virtual machine and make sure the output matches the genuine Mac exactly:
```
system_profiler SPHardwareDataType
ioreg -l | grep -m 1 board-id
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM
ioreg -l -p IODeviceTree | grep \"system-id
```

The value of `DmiSystemUuid` in the script needs to be equal to the value of `Hardware UUID` from the command `system_profiler SPHardwareDataType`, and the value of SYSTEM_UUID needs to be equal to the value of `system-id` from the command `ioreg -l -p IODeviceTree | grep \"system-id`. Both appear in the script in the exact format they appear on a genuine Mac.

The Apple ID has to be active, you cannot register a new Apple ID because that would require assigning more NVRAM and SMC values than the script provides.

If you don't have a genuine Mac, [there are guides on the internet for generating genuine-like values](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial), but no support is offered for non-genuine values.

**Comment by sirtsunami** [comment]
i also need help, how do i run the commands?

**Comment by bkarlan** [comment]
Same here.  How do you "run" the commands?  What does that look like and how is it done?  Many of us have left Apple, Google and Mircrosoft and it's not without it's major inconveniences and we have a large learning curve.  I only want iMessage to run as I have not yet bought an /e/ Android phone that can sync messages with Manjaro.  So meanwhile, can someone explain what it means to "run" the commands?

**Comment by Itai-Nelken** [comment]
> Same here. How do you "run" the commands? What does that look like and how is it done? Many of us have left Apple, Google and Mircrosoft and it's not without it's major inconveniences and we have a large learning curve. I only want iMessage to run as I have not yet bought an /e/ Android phone that can sync messages with Manjaro. So meanwhile, can someone explain what it means to "run" the commands?

run them in the terminal app.
you open the terminal
copy-n-paste the commands

**Comment by bkarlan** [comment]
Ok, but the commands need to be in terminal.  So you are saying to run the terminal app in the Mac VM?

**Comment by brahuna** [comment]
> Ok, but the commands need to be in terminal. So you are saying to run the terminal app in the Mac VM?
> 
> And in regards to exactly what you need filled it, it's not clear. It's mentioned `The value of DmiSystemUuid in the script needs to be equal to the value of Hardware UUID` but nowhere does the script mention `DmiSystemUuid`. So where would that go exactly? Addtionally, in the same line it's mentioned that this data needs to come from `from the command system_profiler SPHardwareDataType`. Well, where do you get that info, the original Mac or the VM Mac or the Linux machine running the VM, it doesn't say. The same can be said for the next line `and the value of SYSTEM_UUID needs to be equal to the value of system-id from the command ioreg -l -p IODeviceTree | grep \"system-id`. `SYSTEM_UUID` is not in the command lines that are listed so where does that go? It's mentioned to find them by running the command `ioreg -l -p IODeviceTree | grep \"system-id`. Same questions here, where is that data found?
> 
> ```
> system_profiler SPHardwareDataType
> ioreg -l | grep -m 1 board-id
> nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB
> nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM
> ioreg -l -p IODeviceTree | grep \"system-id
> ```

Anybody have any luck getting this information from those commands and where to set said info?

**Comment by myspaghetti** [comment]
Small update, [the script can attempt to copy the NVRAM and EFI values automatically starting with version 0.98.7](https://github.com/myspaghetti/macos-virtualbox/compare/1e21924..7c97b32) by setting the `get_parameters_from_macOS_host` variable to "`yes`"
