### ISSUE TITLE
boot fails after some changes

### ISSUE THREAD

**Issue by SamimSdz** [myspaghetti/macos-guest-virtualbox#165]
Hi Again :))
I have successfully booted up the OS but after shutdown, I've removed temp files with stage `delete_temporary_files` command, changed resolution with command  `VBoxManage setextradata "macOS"  "VBoxInternal2/EfiGraphicsResolution" "1600x900"` and finally moved `macOS.vbox` (not the  `macOS.vdi`) to a new location. As you see below it seems like I've broke something within these changes. Can you help me please ?
I actually tried to restore files to the original location and restore the resolution to what it was, but it still doesn't work !

VBox :
![image](https://user-images.githubusercontent.com/29577616/75435672-a18c0380-5968-11ea-8f87-3cfe413b8d22.png)d

Logs : [VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/4261082/VBox.log)

**Comment by myspaghetti** [comment]
The VirtualBox log is fine, the problem is with the macOS installation. It's possible another file got corrupted during/after the installation of macOS. You should run a disk integrity check like `gparted` or [Ubuntu Disks](https://help.ubuntu.com/stable/ubuntu-help/disk-check.html.en) on your host to check the file system and the physical storage device.
