### ISSUE TITLE
See Apple logo briefly then shuts down

### ISSUE THREAD

**Issue by mikekenyon99** [myspaghetti/macos-guest-virtualbox#166]
I'm running the latest version of the script (29/02/20) and when it boots for the first time I see the grey Apple logo for the briefest of time and then the machine shuts down.   Where is the log file created so I can see what is causing the error and report back here?

I'm trying to install Catalina btw

Mike

**Comment by myspaghetti** [comment]
Hi! There's no log for the script, the only output is what you see in the terminal. VirtualBox creates a log but if the machine boots and shuts down it means the issue is very likely not with VirtualBox.

If you want to troubleshoot the issue please attach:
* The `VBox.log` file which [can be found in the virtual machine's directory](https://blogs.oracle.com/scoter/virtualbox-log-files-v2)
* The `md5sums.txt` file that results from the following command when run on the script's working directory: `find . -maxdepth 1 -type f -name 'Catalina*' -exec md5sum {} \; > md5sums.txt` # if you're on macOS use `md5` instead of `md5sum`

**Comment by mikekenyon99** [comment]
Hi - not sure what's gone on my machine.  I rebooted, tried creating a Mojave VirtualBox (worked) and then tried the Catalina one again - this time it went through fine!  Not sure what the difference is/was.  However, if it fails again then I will use those troubleshooting tips you mention so I can gather the data.  Is it worth putting this in the Wiki?

**Comment by myspaghetti** [comment]
Good to hear it worked out. No need for a wiki page that says "try turning it off then on again" though.

**Comment by mikekenyon99** [comment]
> Good to hear it worked out. No need for a wiki page that says "try turning it off then on again" though.

Lol! However I meant in the wiki for how you produce the log files for diagnosis.
