### ISSUE TITLE
The Num Lock key does not work

### ISSUE THREAD

**Issue by JFLarvoire** [myspaghetti/macos-guest-virtualbox#190]
Whether Num Lock is on or off, the numeric keypad always generates numbers in the MacOS VM.  
This is a problem on my laptop, which has ridiculously small Home/End/PageUp/PageDown keys. So I usually leave Num Lock off to use the normal-sized keys of the numeric keypad.  
Is there a way to handle the Num Lock key in the MacOS VM?

**Comment by JFLarvoire** [comment]
Well the script does have an array with scancodes mappings, so I thought that maybe the Num Lock keys was a missing entry?

**Comment by myspaghetti** [comment]
Hi, general configuration of macOS and VirtualBox is beyond the scope of this script. The issue is closed but unlocked; anyone may reply if they want to.

The keyboard scancodes are for sending keys to VirtualBox guests from the host, they have no effect on the keyboard configuration within the guest.
