### ISSUE TITLE
macOS host

### ISSUE THREAD

**Issue by TmNguyen12** [myspaghetti/macos-guest-virtualbox#39]
I went through and followed along with the shell script until it finished. During the ensuing installation process, it freezes at "Installing Mojave, 12 minutes remaining." 

Virtualbox 6.0.4
Host OS: macOS Mojave 10.14.3
<img width="917" alt="screen shot 2019-03-05 at 12 12 34 am 1" src="https://user-images.githubusercontent.com/13756633/53790287-78629f80-3edb-11e9-82a6-26da7a5efc83.png">

**Comment by img2tab** [comment]
This script is not tested on macOS hosts, maybe some day I'll get around to implementing this feature.

**Comment by deepio** [comment]
- [x] Switch to brew installation of bash rather than apple core `#!/usr/local/bin/bash` v5.0.7-release
- [x] Comment out line 114 (Exit on MacOS)
- [x] line 128 replace `head` with `ghead`, so that gnu head is used instead of apple's head. Having installed coreutils with brew.

```
Trying to find macOS Mojave InstallAssistant download URL
csplit: *}: bad repetition count
expr: syntax error
Couldn't find the requested download URL in the Apple catalog. Exiting.
```
macos-guest-virtualbox.sh:344 
- `tac "${macOS_release_name}_sucatalog" | csplit - '/InstallAssistantAuto.smd/+1' '{*}' -f "${macOS_release_name}_sucatalog_" -s`

I presume csplit is a little different on MacOS too.

**Comment by myspaghetti** [comment]
@deepio Thank you very much.
