### ISSUE TITLE
SHA1 checksum for downloads

### ISSUE THREAD

**Issue by legale** [myspaghetti/macos-guest-virtualbox#57]
You have made awesome script. But one thing that could be improved is src files cache. Is it possible to download src dmg files directly by the script and then put them to the VM?

**Comment by legale** [comment]
Maybe the easiest way is use something line genisoimage for the downloaded files then mount iso to the VM.

**Comment by legale** [comment]
At least baseSystem.dmg wouldn't downloaded twice.

**Comment by legale** [comment]
It would also be nice to add file consistency checking.

**Comment by legale** [comment]
Also why not to add 
curl -C - 
option to allow resuming broken downloads.

**Comment by img2tab** [comment]
Thanks for all the suggestions, they're all good and I've considered all of them in the past, and I might implement them at some point.

>Is it possible to download src dmg files directly by the script and then put them to the VM?

Yes, with VirtualBox 6 and `RTIsoMaker`. See [issue 55](https://github.com/img2tab/macos-guest-virtualbox/issues/55).

>use something line genisoimage

Creating a temporary ISO was my first thought when writing the script, but this would add a dependency and increase the minimum space requirement, which I'd rather avoid as 37.5GB is already steep. I would switch to a temporary ISO file if it allows me to bypass using the temporary `Install.vdi` file and save space. This can be achieved through partitioning the target disk into two partitions, using one as the temporary install partition and the other as the target, then after the installer initially populates the target volume, remove the install partition and expand the target partition to fill the entire `vdi`. I am not sure how macOS will handle this partitioning, but I have a feeling it'll be prone to failure. Still, it's a viable solution.

>add file consistency checking

The sha1 checksum is supposed to be supplied by [InstallInfo.plist](http://swcdn.apple.com/content/downloads/21/07/041-59913/m210y0lkn7bsiqsi98vfuyk08x2z4to1qk/InstallInfo.plist) but the value fields are empty. If they were available I'd check against them.

>` curl -C -`

I avoided this on older versions of the script because the version of `curl` provided by `BaseSystem.vdi` was buggy, but now I see the `-C -` argument works properly so I'll put it in the script.

**Comment by myspaghetti** [comment]
Closing as "wontfix"; security-conscious users might want to check other projects like [https://github.com/notpeter/apple-installer-checksums](https://github.com/notpeter/apple-installer-checksums) or obtain the checksums from Apple.
